### ISSUE TITLE
Typo of "Reference" instead of "Collision"

### ISSUE THREAD

**Issue by McGravel** [bonjorno7/base#1]
Just a slight typo, doesn't appear in the README's screenshot so it doesn't look like it'll cause any end-user confusion
https://github.com/bonjorno7/blender_source_extras/blob/b677f81b057752a19e0fca43a2384f0a3e0129b0/qc_generator.py#L43

**Comment by bonjorno7** [comment]
fixed, will commit with the next update

**Comment by bonjorno7** [comment]
that's right the time has come to close your issue yaaas
