### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Toko-de** [bonjorno7/base#3]
Greetings,

I would like to use your addon but I get an error during the instalation, tried (Win7, 64bit) Blender 2.8 and 2.79b, same error for both of them.

Screenshot: ![br_blender_base](https://user-images.githubusercontent.com/48996232/55089680-10544300-50ae-11e9-905c-0757a9fc0ca6.png)

(https://ibb.co/0qxWn5v)

**Comment by bonjorno7** [comment]
try again, it should work now
if not, I'm certain it's an issue with blender
perhaps you could navigate to your blender appdata add-ons folder
"C:\Users\Jorijn\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons" for me
and delete the base-master folder there, and delete the pycache folder
then try installing the latest version of the add-on again

**Comment by Toko-de** [comment]
Hey Bonjorno7,

thanks for the answer, but it seems not to work. :(
Is it just me, is it working for you? 
Feelsbad..

![blender_br](https://user-images.githubusercontent.com/48996232/55289678-c333e200-53c9-11e9-971f-4f10eb4d89cd.png)

greetings

**Comment by bonjorno7** [comment]
Contact me on discord @bonjorno7#3007 and we'll work through it.

**Comment by bonjorno7** [comment]
here's a link to the discord
https://discord.gg/N35zhHm
I'll close your issue now
